apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: e3x5fxp6d-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-bdcee7700f.x1ui.p3.openshiftapps.com/rhtap/rhtap-qe:9a81c51e61b51bbd0ddd3078bc26f4674ed83cfb@sha256:08e8fc3c5e422811277cfb2dc8e7c7d8d79fa3b708f2fe3e3c166bb14c7baa08
          name: container-image
